sources:
  - name: RequestsGRPC
    handler:
      grpc:
        endpoint: localhost:50051
        metaData:
          token: "{context.headers['some_auth_token']}"
    transforms:
      - prefix:
          value: TEST_
          includeRootOperations: true